### ISSUE TITLE
`object.hasown` breaks eslint react/jsx-no-duplicate-props

### ISSUE THREAD

**Issue by promer94** [SukkaW/nolyfill#1]
Repro: 
https://github.com/promer94/nolyfill-eslint

<img width="1353" alt="CleanShot 2023-08-10 at 10 37 35@2x" src="https://github.com/SukkaW/nolyfill/assets/15878786/03d177a8-f21d-4439-ba58-b6c1fbd4d6a2">

**Comment by SukkaW** [comment]
Fixed by https://github.com/SukkaW/nolyfill/commit/7c414df281573126ed8121aed8d494f84b11e79a and is included in the `1.0.4`~
