### ISSUE TITLE
nolyfill for `Function.prototype.name` is incorrect

### ISSUE THREAD

**Issue by jdalton** [SukkaW/nolyfill#104]
The `Function.prototype.name` is incorrect:
https://github.com/SukkaW/nolyfill/blob/v1.0.30/packages/data/es-shim-like/src/function.prototype.name.ts

The `Function.prototype.name` package gets the name of the function. The current nolyfill will return the '' of the `Function.prototype.name`.

**Comment by SukkaW** [comment]
Fixed by https://github.com/SukkaW/nolyfill/pull/106 and the bugfix was included in version 1.0.40, closing~
