### ISSUE TITLE
[package request] `is-core-module`

### ISSUE THREAD

**Issue by antfu** [SukkaW/nolyfill#25]
https://www.npmjs.com/package/is-core-module

I think it can be implemented as

```ts
const { builtinModules } = require('node:module')

module.exports = (n) => n.startsWith('node:') ||  builtinModules.includes(n)
```

**Comment by ljharb** [comment]
Nope, it can't. `node:` isn't available in node 12, and `node:nonexistent` isn't a core module anyways.

**Comment by antfu** [comment]
But to me, `node:` is a node-specific namespace, whether it does not exist or isn't supported, they are not going to be resolved to anything else anyway. Or a plain `builtinModules.includes(name)` is actually quite enough I suppose.

**Comment by ljharb** [comment]
That's not how `is-core-module` works. If it returns `true`, the module *must* be requireable.

**Comment by SukkaW** [comment]
Also, IIRC `is-core-module` accepts the second argument for a specific Node.js version. The usage of that second argument is quite common in toolchain packages.

**Comment by antfu** [comment]
Make sense, closing for now
