### ISSUE TITLE
nolyfill request: `is-typedarray`

### ISSUE THREAD

**Issue by wojtekmaj** [SukkaW/nolyfill#52]
I see that in da6acaa64784a954f85e082f64e8a07fb8feb4af nolyfill for `is-typed-array` has been added. But there's also `is-typedarray` (without the dash), which, according to my brief research does the same, has similar (insane) amount of downloads, and has been updated 9 years ago. Looks like a low hanging fruit?

**Comment by SukkaW** [comment]
> Looks like a low hanging fruit?

Probably not.

`is-typedarray` is small. The installation size of `is-typedarray` (without the dash) is only `4.4 KiB`, while the installation size of `is-typed-array` (with the dash) is `309 KiB`.

`is-typedarray` has no dependency at all, and `is-typed-array` (with the dash) has 1 direct dependency and 15 transitive dependencies.

In short, `is-typedarray` (without the dash) is the ideal package!

**Comment by ljharb** [comment]
It doesn’t support BigInt typed arrays, and uses a technique that’s not robust.
