### ISSUE TITLE
Bug: CLI can't be installed to node_modules/.bin

### ISSUE THREAD

**Issue by NWYLZW** [SukkaW/nolyfill#7]
https://github.com/SukkaW/nolyfill/blob/19762ae40ef825f5ed941ab1db326a4583262ff7/packages/cli/package.json#L6

```json
"bin": { "nolyfill": "bin/nolyfill.js" },
```

The package carrying the scope cannot be simply registered in the bin, and the name of the command needs to be specified.

[If you have a single executable, and its name should be the name of the package, then you can just supply it as a string.](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bin:~:text=If%20you%20have%20a%20single%20executable%2C%20and%20its%20name%20should%20be%20the%20name%20of%20the%20package%2C%20then%20you%20can%20just%20supply%20it%20as%20a%20string.)

**Comment by SukkaW** [comment]
Fixed in the latest version.
