### ISSUE TITLE
pnpm workspace

### ISSUE THREAD

**Issue by o-az** [SukkaW/nolyfill#82]
How can I use nolyfill in a pnpm workspace? Currently I get the following error:

```sh
pnpm dlx nolyfill

[AggregateError: All promises were rejected] {
  [errors]: [
    Error: ENOENT: no such file or directory, access '/packages/core/yarn.lock'
        at async Object.access (node:internal/fs/promises:608:10)
        at async Promise.any (index 0)
        at async Object.detectPackageManager
        ...
```

**Comment by AhmedBaset** [comment]
Do you run it in the root (as level as `pnpm-lock.yaml`)?

**Comment by o-az** [comment]
yes but it doesn't apply to workspaces when I run in root

**Comment by SukkaW** [comment]
@o-az nolyfill already implemented pnpm workspaces finding (using the `@pnpm/workspace.find-packages` package):

https://github.com/SukkaW/nolyfill/blob/691cbef8a23bb7e7c7579369e66f755ed45b1804/packages/tools/cli/src/lockfile/pnpm.ts#L6C53-L6C76

This should allow nolyfill to work w/ pnpm workspaces based monorepo.
