### ISSUE TITLE
Support safe-buffer and safer-buffer

### ISSUE THREAD

**Issue by RDIL** [SukkaW/nolyfill#87]
https://www.npmjs.com/package/safe-buffer https://www.npmjs.com/package/safer-buffer

Both of these packages exist to port new buffer-related features to older versions of Node. They are pretty well used (109m and 38m monthly DLs respectively), so I think there would be a benefit to including these two.

**Comment by SukkaW** [comment]
Do note that `safer-buffer` does have an export `safer-buffer/dangerous`. But it seems that no one is using this:

https://grep.app/search?q=safer-buffer/dangereous
https://github.com/search?q=safer-buffer%2Fdangereous+NOT+language%3AMarkdown+NOT+language%3AHTML&type=code

**Comment by RDIL** [comment]
Maybe it would be worth adding a `safer-buffer/dangerous.js` where it’s literally just `throw new Error("nolyfill unsupported: safer-buffer/dangerous")`?
